g [T1] =  - BiVU(p4,p1,p3)*p4(nu1)*p3(nu2)*mt + BiVU(p4,p1,p3)*p4(nu2)*p3(nu1)
      *mt + BiVU(p4,p2,p3)*p4(nu1)*p3(nu2)*mt - BiVU(p4,p2,p3)*p4(nu2)*p3(nu1)
      *mt ;
g [T2] = BiVU(p4,p1,p3)*p3(nu1)*p3(nu2)*mt + BiVU(p4,p2,p3)*p3(nu1)*p3(nu2)*mt ;
g [T3] = BiVU(p4,p1,p3)*p4(nu1)*p4(nu2)*mt + BiVU(p4,p2,p3)*p4(nu1)*p4(nu2)*mt ;
g [T4] = BiVU(p4,p1,p3)*p4(nu1)*p3(nu2)*mt + BiVU(p4,p1,p3)*p4(nu2)*p3(nu1)*mt
       + BiVU(p4,p2,p3)*p4(nu1)*p3(nu2)*mt + BiVU(p4,p2,p3)*p4(nu2)*p3(nu1)*mt ;
g [T5] =  - BiVU(p4,p1,p3)*p4(nu1)*p3(nu2)*mt + BiVU(p4,p1,p3)*p4(nu2)*p3(nu1)
      *mt - BiVU(p4,p2,p3)*p4(nu1)*p3(nu2)*mt + BiVU(p4,p2,p3)*p4(nu2)*p3(nu1)
      *mt ;
g [T6] = BiVU(p4,p1,p3)*p3(nu1)*p3(nu2)*mt - BiVU(p4,p2,p3)*p3(nu1)*p3(nu2)*mt ;
g [T7] = BiVU(p4,p1,p3)*p4(nu1)*p4(nu2)*mt - BiVU(p4,p2,p3)*p4(nu1)*p4(nu2)*mt ;
g [T8] = BiVU(p4,p1,p3)*p4(nu1)*p3(nu2)*mt + BiVU(p4,p1,p3)*p4(nu2)*p3(nu1)*mt
       - BiVU(p4,p2,p3)*p4(nu1)*p3(nu2)*mt - BiVU(p4,p2,p3)*p4(nu2)*p3(nu1)*mt ;
g [T9] =  - BiVU(p4,p1,p2,p3)*p4(nu1)*p3(nu2) + BiVU(p4,p1,p2,p3)*p4(nu2)*
      p3(nu1) + BiVU(p4,p2,p1,p3)*p4(nu1)*p3(nu2) - BiVU(p4,p2,p1,p3)*p4(nu2)*
      p3(nu1) ;
g [T10] = BiVU(p4,p3)*p4(nu1)*p3(nu2)*mt^2 + BiVU(p4,p3)*p4(nu2)*p3(nu1)*mt^2 ;
g [T11] = BiVU(p4,p3)*p3(nu1)*p3(nu2)*s12 ;
g [T12] = BiVU(p4,p3)*p4(nu1)*p4(nu2)*s12 ;
g [T13] =  - BiVU(p4,p3)*p4(nu1)*p3(nu2)*mt^2 + BiVU(p4,p3)*p4(nu2)*p3(nu1)*
      mt^2 ;
g [T14] = BiVU(p4,p1,p2,p3)*p3(nu1)*p3(nu2) - BiVU(p4,p2,p1,p3)*p3(nu1)*
      p3(nu2) ;
g [T15] = BiVU(p4,p1,p2,p3)*p4(nu1)*p4(nu2) - BiVU(p4,p2,p1,p3)*p4(nu1)*
      p4(nu2) ;
g [T16] = BiVU(p4,p1,p2,p3)*p4(nu1)*p3(nu2) + BiVU(p4,p1,p2,p3)*p4(nu2)*
      p3(nu1) - BiVU(p4,p2,p1,p3)*p4(nu1)*p3(nu2) - BiVU(p4,p2,p1,p3)*p4(nu2)*
      p3(nu1) ;

g [T1d] =  - BiUV(p3,p1,p4)*p4(mu1)*p3(mu2)*mt + BiUV(p3,p1,p4)*p4(mu2)*
      p3(mu1)*mt + BiUV(p3,p2,p4)*p4(mu1)*p3(mu2)*mt - BiUV(p3,p2,p4)*p4(mu2)*
      p3(mu1)*mt ;
g [T2d] = BiUV(p3,p1,p4)*p3(mu1)*p3(mu2)*mt + BiUV(p3,p2,p4)*p3(mu1)*p3(mu2)*
      mt ;
g [T3d] = BiUV(p3,p1,p4)*p4(mu1)*p4(mu2)*mt + BiUV(p3,p2,p4)*p4(mu1)*p4(mu2)*
      mt ;
g [T4d] = BiUV(p3,p1,p4)*p4(mu1)*p3(mu2)*mt + BiUV(p3,p1,p4)*p4(mu2)*p3(mu1)*
      mt + BiUV(p3,p2,p4)*p4(mu1)*p3(mu2)*mt + BiUV(p3,p2,p4)*p4(mu2)*p3(mu1)*
      mt ;
g [T5d] =  - BiUV(p3,p1,p4)*p4(mu1)*p3(mu2)*mt + BiUV(p3,p1,p4)*p4(mu2)*
      p3(mu1)*mt - BiUV(p3,p2,p4)*p4(mu1)*p3(mu2)*mt + BiUV(p3,p2,p4)*p4(mu2)*
      p3(mu1)*mt ;
g [T6d] = BiUV(p3,p1,p4)*p3(mu1)*p3(mu2)*mt - BiUV(p3,p2,p4)*p3(mu1)*p3(mu2)*
      mt ;
g [T7d] = BiUV(p3,p1,p4)*p4(mu1)*p4(mu2)*mt - BiUV(p3,p2,p4)*p4(mu1)*p4(mu2)*
      mt ;
g [T8d] = BiUV(p3,p1,p4)*p4(mu1)*p3(mu2)*mt + BiUV(p3,p1,p4)*p4(mu2)*p3(mu1)*
      mt - BiUV(p3,p2,p4)*p4(mu1)*p3(mu2)*mt - BiUV(p3,p2,p4)*p4(mu2)*p3(mu1)*
      mt ;
g [T9d] = BiUV(p3,p1,p2,p4)*p4(mu1)*p3(mu2) - BiUV(p3,p1,p2,p4)*p4(mu2)*
      p3(mu1) - BiUV(p3,p2,p1,p4)*p4(mu1)*p3(mu2) + BiUV(p3,p2,p1,p4)*p4(mu2)*
      p3(mu1) ;
g [T10d] = BiUV(p3,p4)*p4(mu1)*p3(mu2)*mt^2 + BiUV(p3,p4)*p4(mu2)*p3(mu1)*mt^2 ;
g [T11d] = BiUV(p3,p4)*p3(mu1)*p3(mu2)*s12 ;
g [T12d] = BiUV(p3,p4)*p4(mu1)*p4(mu2)*s12 ;
g [T13d] =  - BiUV(p3,p4)*p4(mu1)*p3(mu2)*mt^2 + BiUV(p3,p4)*p4(mu2)*p3(mu1)*
      mt^2 ;
g [T14d] =  - BiUV(p3,p1,p2,p4)*p3(mu1)*p3(mu2) + BiUV(p3,p2,p1,p4)*p3(mu1)*
      p3(mu2) ;
g [T15d] =  - BiUV(p3,p1,p2,p4)*p4(mu1)*p4(mu2) + BiUV(p3,p2,p1,p4)*p4(mu1)*
      p4(mu2) ;
g [T16d] =  - BiUV(p3,p1,p2,p4)*p4(mu1)*p3(mu2) - BiUV(p3,p1,p2,p4)*p4(mu2)*
      p3(mu1) + BiUV(p3,p2,p1,p4)*p4(mu1)*p3(mu2) + BiUV(p3,p2,p1,p4)*p4(mu2)*
      p3(mu1) ;
