jobs:
  - reduce_user_defined_system:
      input_system: {files: [Eqs.kira], config: false}
      select_integrals:
        select_mandatory_list:
         - [Wanted.kira]
      ### determine MI
      run_initiate: true
      ### run reduction
      run_triangular: true
      run_back_substitution: false
      run_firefly: true
      factor_scan: true
  - kira2math:
      target:
        - [Wanted.kira]
