integralfamilies:
  - name: "PL1"
    loop_momenta: [k1]
    propagators:
      - [ "k1", 0 ] #k1^2 - 0
      - [ "k1-p2", 0] #(k1-p1)^2 
      - [ "k1+p1+p3+p4", 0 ] 
      - [ "k1+p3", mt^2 ] #(k1+p1)^2 - mt^2
      - [ "k1+p3+p4", 0 ] 
