*
* file generated by qgraf-3.6.5
*
*  config= noblanks ;
*  output= 'output_GoodNotation' ;
*  style= 'form.sty.mine' ;
*  model= 'wtt';
*  in= quark, antiquark ;
*  out= top, antitop, wboson;
*  loops= 0 ;
*  loop_momentum= ;
*  options=  floop ;
*
 
id d1= (+1)*
 pol(quark(-1,p1))* pol(antiquark(-3,p2))*
 pol(top(-2,q1))* pol(antitop(-4,q2))* pol(wboson(-6,q3))*
 prop(quark(1,2,p1-q3))*
 prop(gluon(3,4,q1+q2))*
 vrtx(antiquark(2,-p1+q3),quark(-1,p1),wboson(-6,-q3))*
 vrtx(antitop(-2,-q1),top(-4,-q2),gluon(3,q1+q2))*
 vrtx(antiquark(-3,p2),quark(1,p1-q3),gluon(4,-q1-q2)) ;
 
id d2= (+1)*
 pol(quark(-1,p1))* pol(antiquark(-3,p2))*
 pol(top(-2,q1))* pol(antitop(-4,q2))* pol(wboson(-6,q3))*
 prop(quark(1,2,-p2+q3))*
 prop(gluon(3,4,q1+q2))*
 vrtx(antiquark(-3,p2),quark(1,-p2+q3),wboson(-6,-q3))*
 vrtx(antitop(-2,-q1),top(-4,-q2),gluon(3,q1+q2))*
 vrtx(antiquark(2,p2-q3),quark(-1,p1),gluon(4,-q1-q2)) ;

