**************************************************************************
*********** User input: Number of Diagrams generated by QGRAF    *********
**************************************************************************

# $NumberOfDiagrams = 8;


*gs = strong/weak coupling constant, Feps = Feynman's i epsilon prescription, mt, mh, mw = top/higgs/W-boson mass
Symbols gs, gw, Feps, mt, mh, mw ;


*Mandelstamvariables
autodeclare symbols s;

*We set mu = nu = 0 to overrule automated summation of these indices. One can later sum over these by using the command sum (see Documentation Sec. Vectors and Indices ) 
autodeclare index mu=0, nu = 0, rho = 0, sigma = 0;


*We define the momenta p as a function not a vector. This will be changed later.
autodeclare functions p;
functions TopPropagator,  QuarkPropagator, ExternalAntiTop, ExternalTop, ExternalAntiTopC, ExternalTopC, VertexOfTypeTTH;

*function for denominator ~ ()^-1
cfunctions GluonPropagator, VertexOfTypeGGG, ExternalGluon , denom, num;

*SUN is the N in SU(N). NGen is the number of generators T of SU(N)
symbols SUN, NGen, CF, CA;
autodeclare index ColFun = SUN, col = NGen;
Ntensor T;
Tensor TLorentz, TLorentzC;
Ctensor fcol(antisymmetric); 

*Dummy variables and functions
symbols x, y, z, [];
autodeclare symbols aux;
autodeclare functions HelpF;

cfunctions ColTr(cyclic), TProduct, SpinorCNumber, SpinorCNumberC, Sp(symmetric);
vectors eps1, eps2, eps1C, eps2C;

autodeclare vectors vecp;

autodeclare symbols ColFactor;


* The number of form factors and projectors is by definition the same, but to have a clearer code I use to different variables.
# $NumberOfFormFactors = 16;
# $NumberOfProjectors  = 16;

autodeclare symbols ProjectorCoefficient, GRAMProjector;
autodeclare tensors ProjectorTensor;


autodeclare function ConjugatedExternal;




ntensor T;

Dimension D;
.global
