#define rule1 "0"
#define rule2 "0"
#define rule3 "0"
#define rule4 "0"
#define rule5 "0"
#define rule6 "0"
#define rule7 "0"
#define rule8 "0"
#define rule9 "0"
#define rule10 "0"
#define rule11 "0"
#define rule12 "0"
#define rule13 "0"
#define rule14 "0"
#define rule15 "0"
#define rule16 "0"
#define rule17 "0"
#define rule18 "0"
#define rule19 "0"
#define rule20 "0"
#define rule21 "0"
#define rule22 "0"
#define rule23 "0"
#define rule24 "0"
#define rule25 "0"
#define rule26 "0"
#define rule27 "0"
#define rule28 "0"
#define rule29 "0"
#define rule30 "0"
#define rule31 "0"
#define rule32 "0"
#define rule33 "0"
#define rule34 "0"
#define rule35 "0"
#define rule36 "0"
#define rule37 "0"
#define rule38 "0"
#define rule39 "0"
#define rule40 "0"
#define rule41 "0"
#define rule42 "0"
#define rule43 "0"
#define rule44 "0"
#define rule45 "0"
#define rule46 "0"
#define rule47 "0"
#define rule48 "0"
#define rule49 "0"
#define rule50 "0"
#define rule51 "0"
#define rule52 "0"
#define rule53 "0"
#define rule54 "0"
#define rule55 "0"
#define rule56 "0"
#define rule57 "0"
#define rule58 "0"
#define rule59 "0"
#define rule60 "0"
#define rule61 "0"
#define rule62 "0"
#define rule63 "0"
#define rule64 "0"
#define rule65 "0"
#define rule66 "0"
#define rule67 "0"
#define rule68 "0"
#define rule69 "0"
#define rule70 "0"
#define rule71 "0"
#define rule72 "0"
#define rule73 "0"
#define rule74 "0"
#define rule75 "0"
#define rule76 "0"
#define rule77 "0"
#define rule78 "0"
#define rule79 "0"
#define rule80 "0"
#define rule81 "0"
#define rule82 "0"
#define rule83 "0"
#define rule84 "0"
#define rule85 "0"
#define rule86 "0"
#define rule87 "0"
#define rule88 "0"
#define rule89 "0"
#define rule90 "0"
#define rule91 "0"
#define rule92 "0"
#define rule93 "0"
#define rule94 "0"
#define rule95 "0"
#define rule96 "0"
#define rule97 "0"
#define rule98 "0"
#define rule99 "0"
#define rule100 "0"
#define rule101 "0"
#define rule102 "0"
#define rule103 "0"
#define rule104 "0"
#define rule105 "0"
#define rule106 "0"
#define rule107 "0"
#define rule108 "0"
#define rule109 "0"
#define rule110 "0"
#define rule111 "0"
#define rule112 "0"
#define rule113 "0"
#define rule114 "0"
#define rule115 "0"
#define rule116 "0"
#define rule117 "0"
#define rule118 "0"
#define rule119 "0"
#define rule120 "0"
#define rule121 "0"
#define rule122 "0"
#define rule123 "0"
#define rule124 "0"
#define rule125 "0"
#define rule126 "0"
#define rule127 "0"
#define rule128 "0"
#define rule129 "0"
#define rule130 "0"
#define rule131 "0"
#define rule132 "0"
#define rule133 "0"
#define rule134 "0"
#define rule135 "0"
#define rule136 "0"
#define rule137 "0"
#define rule138 "0"
#define rule139 "0"
#define rule140 "0"
#define rule141 "0"
#define rule142 "0"
#define rule143 "0"
#define rule144 "0"
#define rule145 "0"
#define rule146 "0"
#define rule147 "0"
#define rule148 "0"
#define rule149 "0"
#define rule150 "0"
#define rule151 "0"
#define rule152 "0"
#define rule153 "0"
#define rule154 "0"
#define rule155 "0"
#define rule156 "0"
#define rule157 "0"
#define rule158 "0"
#define rule159 "0"
#define rule160 "0"
#define rule161 "0"
#define rule162 "0"
#define rule163 "0"
#define rule164 "0"
#define rule165 "0"
#define rule166 "0"
#define rule167 "0"
#define rule168 "0"
#define rule169 "0"
if (match(qq1*s));
 redefine rule1 "1";
 $repeat = 1;
endif;
if (match(qq2*t));
 redefine rule2 "1";
 $repeat = 1;
endif;
if (match(D*qq10));
 redefine rule3 "1";
 $repeat = 1;
endif;
if (match(D*qq11));
 redefine rule4 "1";
 $repeat = 1;
endif;
if (match(qq10*qq11));
 redefine rule5 "1";
 $repeat = 1;
endif;
if (match(D*qq12));
 redefine rule6 "1";
 $repeat = 1;
endif;
if (match(qq10*qq12));
 redefine rule7 "1";
 $repeat = 1;
endif;
if (match(qq11*qq12));
 redefine rule8 "1";
 $repeat = 1;
endif;
if (match(D*qq13));
 redefine rule9 "1";
 $repeat = 1;
endif;
if (match(qq10*qq13));
 redefine rule10 "1";
 $repeat = 1;
endif;
if (match(qq11*qq13));
 redefine rule11 "1";
 $repeat = 1;
endif;
if (match(qq12*qq13));
 redefine rule12 "1";
 $repeat = 1;
endif;
if (match(D*qq14));
 redefine rule13 "1";
 $repeat = 1;
endif;
if (match(qq10*qq14));
 redefine rule14 "1";
 $repeat = 1;
endif;
if (match(qq11*qq14));
 redefine rule15 "1";
 $repeat = 1;
endif;
if (match(qq12*qq14));
 redefine rule16 "1";
 $repeat = 1;
endif;
if (match(qq13*qq14));
 redefine rule17 "1";
 $repeat = 1;
endif;
if (match(D*qq15));
 redefine rule18 "1";
 $repeat = 1;
endif;
if (match(qq10*qq15));
 redefine rule19 "1";
 $repeat = 1;
endif;
if (match(qq11*qq15));
 redefine rule20 "1";
 $repeat = 1;
endif;
if (match(qq12*qq15));
 redefine rule21 "1";
 $repeat = 1;
endif;
if (match(qq13*qq15));
 redefine rule22 "1";
 $repeat = 1;
endif;
if (match(qq14*qq15));
 redefine rule23 "1";
 $repeat = 1;
endif;
if (match(qq16*qq17));
 redefine rule24 "1";
 $repeat = 1;
endif;
if (match(qq16*qq2));
 redefine rule25 "1";
 $repeat = 1;
endif;
if (match(D*qq3));
 redefine rule26 "1";
 $repeat = 1;
endif;
if (match(qq10*qq3));
 redefine rule27 "1";
 $repeat = 1;
endif;
if (match(qq11*qq3));
 redefine rule28 "1";
 $repeat = 1;
endif;
if (match(qq12*qq3));
 redefine rule29 "1";
 $repeat = 1;
endif;
if (match(qq13*qq3));
 redefine rule30 "1";
 $repeat = 1;
endif;
if (match(qq14*qq3));
 redefine rule31 "1";
 $repeat = 1;
endif;
if (match(qq15*qq3));
 redefine rule32 "1";
 $repeat = 1;
endif;
if (match(D*qq4));
 redefine rule33 "1";
 $repeat = 1;
endif;
if (match(qq10*qq4));
 redefine rule34 "1";
 $repeat = 1;
endif;
if (match(qq11*qq4));
 redefine rule35 "1";
 $repeat = 1;
endif;
if (match(qq12*qq4));
 redefine rule36 "1";
 $repeat = 1;
endif;
if (match(qq13*qq4));
 redefine rule37 "1";
 $repeat = 1;
endif;
if (match(qq14*qq4));
 redefine rule38 "1";
 $repeat = 1;
endif;
if (match(qq15*qq4));
 redefine rule39 "1";
 $repeat = 1;
endif;
if (match(qq3*qq4));
 redefine rule40 "1";
 $repeat = 1;
endif;
if (match(D*qq5));
 redefine rule41 "1";
 $repeat = 1;
endif;
if (match(qq10*qq5));
 redefine rule42 "1";
 $repeat = 1;
endif;
if (match(qq11*qq5));
 redefine rule43 "1";
 $repeat = 1;
endif;
if (match(qq12*qq5));
 redefine rule44 "1";
 $repeat = 1;
endif;
if (match(qq13*qq5));
 redefine rule45 "1";
 $repeat = 1;
endif;
if (match(qq14*qq5));
 redefine rule46 "1";
 $repeat = 1;
endif;
if (match(qq15*qq5));
 redefine rule47 "1";
 $repeat = 1;
endif;
if (match(qq3*qq5));
 redefine rule48 "1";
 $repeat = 1;
endif;
if (match(qq4*qq5));
 redefine rule49 "1";
 $repeat = 1;
endif;
if (match(D*qq6));
 redefine rule50 "1";
 $repeat = 1;
endif;
if (match(qq10*qq6));
 redefine rule51 "1";
 $repeat = 1;
endif;
if (match(qq11*qq6));
 redefine rule52 "1";
 $repeat = 1;
endif;
if (match(qq12*qq6));
 redefine rule53 "1";
 $repeat = 1;
endif;
if (match(qq13*qq6));
 redefine rule54 "1";
 $repeat = 1;
endif;
if (match(qq14*qq6));
 redefine rule55 "1";
 $repeat = 1;
endif;
if (match(qq15*qq6));
 redefine rule56 "1";
 $repeat = 1;
endif;
if (match(qq3*qq6));
 redefine rule57 "1";
 $repeat = 1;
endif;
if (match(qq4*qq6));
 redefine rule58 "1";
 $repeat = 1;
endif;
if (match(qq5*qq6));
 redefine rule59 "1";
 $repeat = 1;
endif;
if (match(qq1*qq7));
 redefine rule60 "1";
 $repeat = 1;
endif;
if (match(qq17*qq2));
 redefine rule61 "1";
 $repeat = 1;
endif;
if (match(qq17*qq8));
 redefine rule62 "1";
 $repeat = 1;
endif;
if (match(qq2*qq8));
 redefine rule63 "1";
 $repeat = 1;
endif;
if (match(D*qq9));
 redefine rule64 "1";
 $repeat = 1;
endif;
if (match(qq10*qq9));
 redefine rule65 "1";
 $repeat = 1;
endif;
if (match(qq11*qq9));
 redefine rule66 "1";
 $repeat = 1;
endif;
if (match(qq12*qq9));
 redefine rule67 "1";
 $repeat = 1;
endif;
if (match(qq13*qq9));
 redefine rule68 "1";
 $repeat = 1;
endif;
if (match(qq14*qq9));
 redefine rule69 "1";
 $repeat = 1;
endif;
if (match(qq15*qq9));
 redefine rule70 "1";
 $repeat = 1;
endif;
if (match(qq3*qq9));
 redefine rule71 "1";
 $repeat = 1;
endif;
if (match(qq4*qq9));
 redefine rule72 "1";
 $repeat = 1;
endif;
if (match(qq5*qq9));
 redefine rule73 "1";
 $repeat = 1;
endif;
if (match(qq6*qq9));
 redefine rule74 "1";
 $repeat = 1;
endif;
if (match(qq7*s));
 redefine rule75 "1";
 $repeat = 1;
endif;
if (match(qq16*s));
 redefine rule76 "1";
 $repeat = 1;
endif;
if (match(qq1*qq16*t));
 redefine rule77 "1";
 $repeat = 1;
endif;
if (match(qq17*qq7*t));
 redefine rule78 "1";
 $repeat = 1;
endif;
if (match(qq8*t));
 redefine rule79 "1";
 $repeat = 1;
endif;
if (match(qq1*qq16*qq8));
 redefine rule80 "1";
 $repeat = 1;
endif;
if (match(qq16*qq7*qq8));
 redefine rule81 "1";
 $repeat = 1;
endif;
if (match(qq17*s));
 redefine rule82 "1";
 $repeat = 1;
endif;
if (match(qq1*qq17*t));
 redefine rule83 "1";
 $repeat = 1;
endif;
if (match(qq20*qq21*s));
 redefine rule84 "1";
 $repeat = 1;
endif;
if (match(qq16*qq7*t));
 redefine rule85 "1";
 $repeat = 1;
endif;
if (match(qq19*qq2));
 redefine rule86 "1";
 $repeat = 1;
endif;
if (match(qq18*qq8*s));
 redefine rule87 "1";
 $repeat = 1;
endif;
if (match(qq1*qq19*t));
 redefine rule88 "1";
 $repeat = 1;
endif;
if (match(qq19*qq7*t));
 redefine rule89 "1";
 $repeat = 1;
endif;
if (match(qq17*qq18*qq19));
 redefine rule90 "1";
 $repeat = 1;
endif;
if (match(qq19*s^2*t));
 redefine rule91 "1";
 $repeat = 1;
endif;
if (match(qq1*qq18));
 redefine rule92 "1";
 $repeat = 1;
endif;
if (match(qq18*s*t^2));
 redefine rule93 "1";
 $repeat = 1;
endif;
if (match(qq1*qq19*qq8));
 redefine rule94 "1";
 $repeat = 1;
endif;
if (match(qq19*qq8*s));
 redefine rule95 "1";
 $repeat = 1;
endif;
if (match(qq1*qq17*qq19));
 redefine rule96 "1";
 $repeat = 1;
endif;
if (match(qq18*qq2));
 redefine rule97 "1";
 $repeat = 1;
endif;
if (match(qq17*qq18*t^2));
 redefine rule98 "1";
 $repeat = 1;
endif;
if (match(qq17*qq19*t^2));
 redefine rule99 "1";
 $repeat = 1;
endif;
if (match(qq16*qq21*t));
 redefine rule100 "1";
 $repeat = 1;
endif;
if (match(qq17*qq21));
 redefine rule101 "1";
 $repeat = 1;
endif;
if (match(qq18*qq7*t^2));
 redefine rule102 "1";
 $repeat = 1;
endif;
if (match(qq19*qq7*qq8));
 redefine rule103 "1";
 $repeat = 1;
endif;
if (match(qq16*qq20*qq8));
 redefine rule104 "1";
 $repeat = 1;
endif;
if (match(qq17*qq19*qq7));
 redefine rule105 "1";
 $repeat = 1;
endif;
if (match(qq18*qq7*qq8));
 redefine rule106 "1";
 $repeat = 1;
endif;
if (match(qq17*qq20));
 redefine rule107 "1";
 $repeat = 1;
endif;
if (match(qq16*qq20*t));
 redefine rule108 "1";
 $repeat = 1;
endif;
if (match(qq16*qq18*qq7));
 redefine rule109 "1";
 $repeat = 1;
endif;
if (match(qq16*qq19*qq7));
 redefine rule110 "1";
 $repeat = 1;
endif;
if (match(qq1*qq16*qq19));
 redefine rule111 "1";
 $repeat = 1;
endif;
if (match(qq1*qq16*qq21));
 redefine rule112 "1";
 $repeat = 1;
endif;
if (match(qq16*qq21*qq7));
 redefine rule113 "1";
 $repeat = 1;
endif;
if (match(qq16*qq20*qq7));
 redefine rule114 "1";
 $repeat = 1;
endif;
if (match(qq17*qq18*qq7));
 redefine rule115 "1";
 $repeat = 1;
endif;
if (match(qq16*qq18*qq8));
 redefine rule116 "1";
 $repeat = 1;
endif;
if (match(qq18*qq19*s^2));
 redefine rule117 "1";
 $repeat = 1;
endif;
if (match(qq1*qq20));
 redefine rule118 "1";
 $repeat = 1;
endif;
if (match(qq2*qq21));
 redefine rule119 "1";
 $repeat = 1;
endif;
if (match(qq20*s^3));
 redefine rule120 "1";
 $repeat = 1;
endif;
if (match(qq16*qq18*t^3));
 redefine rule121 "1";
 $repeat = 1;
endif;
if (match(qq16*qq19*t^3));
 redefine rule122 "1";
 $repeat = 1;
endif;
if (match(qq21*s^2*t));
 redefine rule123 "1";
 $repeat = 1;
endif;
if (match(qq1*qq21*t^3));
 redefine rule124 "1";
 $repeat = 1;
endif;
if (match(qq21*qq7*t^3));
 redefine rule125 "1";
 $repeat = 1;
endif;
if (match(qq2*qq20*s^2));
 redefine rule126 "1";
 $repeat = 1;
endif;
if (match(qq2*qq20*qq7));
 redefine rule127 "1";
 $repeat = 1;
endif;
if (match(qq21*qq8*s));
 redefine rule128 "1";
 $repeat = 1;
endif;
if (match(qq1*qq21*qq8));
 redefine rule129 "1";
 $repeat = 1;
endif;
if (match(qq20*qq7*t^2));
 redefine rule130 "1";
 $repeat = 1;
endif;
if (match(qq20*qq7*qq8));
 redefine rule131 "1";
 $repeat = 1;
endif;
if (match(qq16*qq19*qq8));
 redefine rule132 "1";
 $repeat = 1;
endif;
if (match(qq18*qq19*qq7));
 redefine rule133 "1";
 $repeat = 1;
endif;
if (match(qq16*qq21*qq8));
 redefine rule134 "1";
 $repeat = 1;
endif;
if (match(qq18*qq19*t^3));
 redefine rule135 "1";
 $repeat = 1;
endif;
if (match(qq21*qq7*qq8));
 redefine rule136 "1";
 $repeat = 1;
endif;
if (match(qq20*qq21*t^3));
 redefine rule137 "1";
 $repeat = 1;
endif;
if (match(qq18*qq19*qq8));
 redefine rule138 "1";
 $repeat = 1;
endif;
if (match(qq16*qq18*qq19));
 redefine rule139 "1";
 $repeat = 1;
endif;
if (match(qq16*qq20*qq21));
 redefine rule140 "1";
 $repeat = 1;
endif;
if (match(qq19*qq21*t^3));
 redefine rule141 "1";
 $repeat = 1;
endif;
if (match(qq18*qq21*t^4));
 redefine rule142 "1";
 $repeat = 1;
endif;
if (match(qq19*qq21*s*t));
 redefine rule143 "1";
 $repeat = 1;
endif;
if (match(qq19*qq20*s*t^2));
 redefine rule144 "1";
 $repeat = 1;
endif;
if (match(qq20*qq21*qq7));
 redefine rule145 "1";
 $repeat = 1;
endif;
if (match(qq16*qq18*qq21));
 redefine rule146 "1";
 $repeat = 1;
endif;
if (match(qq18*qq21*s^3));
 redefine rule147 "1";
 $repeat = 1;
endif;
if (match(qq18*qq20*s^2));
 redefine rule148 "1";
 $repeat = 1;
endif;
if (match(qq18*qq21*qq7));
 redefine rule149 "1";
 $repeat = 1;
endif;
if (match(qq18*qq21*qq8));
 redefine rule150 "1";
 $repeat = 1;
endif;
if (match(qq20*qq21*qq8));
 redefine rule151 "1";
 $repeat = 1;
endif;
if (match(qq19*qq20*qq7));
 redefine rule152 "1";
 $repeat = 1;
endif;
if (match(qq19*qq20*t^4));
 redefine rule153 "1";
 $repeat = 1;
endif;
if (match(qq19*qq21*qq8));
 redefine rule154 "1";
 $repeat = 1;
endif;
if (match(qq16*qq19*qq20));
 redefine rule155 "1";
 $repeat = 1;
endif;
if (match(qq18*qq20*qq7));
 redefine rule156 "1";
 $repeat = 1;
endif;
if (match(qq1*qq19*qq21));
 redefine rule157 "1";
 $repeat = 1;
endif;
if (match(qq19*qq21*qq7));
 redefine rule158 "1";
 $repeat = 1;
endif;
if (match(qq18*qq20*s*t));
 redefine rule159 "1";
 $repeat = 1;
endif;
if (match(qq18*qq20*t^3));
 redefine rule160 "1";
 $repeat = 1;
endif;
if (match(qq16*qq19*qq21));
 redefine rule161 "1";
 $repeat = 1;
endif;
if (match(qq19*qq20*qq8));
 redefine rule162 "1";
 $repeat = 1;
endif;
if (match(qq19*qq21*s^2));
 redefine rule163 "1";
 $repeat = 1;
endif;
if (match(qq18*qq20*qq8));
 redefine rule164 "1";
 $repeat = 1;
endif;
if (match(qq16*qq18*qq20));
 redefine rule165 "1";
 $repeat = 1;
endif;
if (match(qq18*qq19*qq21));
 redefine rule166 "1";
 $repeat = 1;
endif;
if (match(qq19*qq20*qq21));
 redefine rule167 "1";
 $repeat = 1;
endif;
if (match(qq18*qq19*qq20));
 redefine rule168 "1";
 $repeat = 1;
endif;
if (match(qq18*qq20*qq21));
 redefine rule169 "1";
 $repeat = 1;
endif;
.sort
Skip;
NSkip `expr';
