---
kinematics :
  incoming_momenta: [ p1, p2, p3, p4, p5 ]
  outgoing_momenta: [  ]
  momentum_conservation: [p5, "- p1 - p2 - p3 -p4"]
  kinematic_invariants:
    - [s12, 2]
    - [s13, 2]
    - [s14, 2]
    - [s23, 2]
    - [s24, 2]
    - [s34, 2]
    - [mt, 1]
    - [mw, 1]
  scalarproduct_rules:
    - [[p1,p1],  0]
    - [[p2,p2],  0]
    - [[p3,p3],  "mt^2"]
    - [[p4,p4],  "mt^2"]
    - [[p5,p5],  "mw^2"]
    - [[p1+p2,p1+p2],  "s12"]
    - [[p1+p3,p1+p3],  "s13"]
    - [[p1+p4,p1+p4],  "s14"]
    - [[p2+p3,p2+p3],  "s23"]
    - [[p2+p4,p2+p4],  "s24"]
#    - [[p3+p4,p3+p4],  "s34"]
  symbol_to_replace_by_one: mt
