**************************************************************************
*********** User input: Number of Diagrams generated by QGRAF    *********
**************************************************************************

* The number of form factors and projectors is by definition the same, but to have a clearer code I use to different variables.
# $NumberOfFormFactors = 16;
# $NumberOfProjectors  = 16;

* gs = strong/weak coupling constant, Feps = Feynman's i epsilon prescription, mt, mh, mw = top/higgs/W-boson mass, Nf = Number of flavors
* dm renormalization parameter
Symbols gs, gw, gY, Feps, mt, mh, mw, Nf, dm(:1);


*Mandelstamvariables
autodeclare symbols s;

*We set mu = nu = 0 to overrule automated summation of these indices. One can later sum over these by using the command sum (see Documentation Sec. Vectors and Indices ) 
autodeclare index mu=0, nu = 0, rho = 0, sigma = 0;
index FermionLine = 0, FermionLineDummy = 0;


*We define the momenta p as a function not a vector. This will be changed later.
functions p1, p2, p3, p4, p5, k1;
vectors eps1, eps2, eps1C, eps2C, veck1, vecp1, vecp2, vecp3, vecp4, vecp5;

functions TopPropagator,  QuarkPropagator, ExternalAntiTop, ExternalTop, ExternalAntiTopC, ExternalTopC, VertexOfTypeTTH;

*function for denominator ~ ()^-1
cfunctions denom, num, RationalFunction, INT;
cfunctions GluonPropagator, GhostPropagator, VertexOfTypeGGG, VertexOfTypeGGGG, ExternalGluon;

*SUN is the N in SU(N). NGen is the number of generators T of SU(N)
symbols SUN, NGen, CF, CA, D;

autodeclare index ColFun = SUN, col = NGen;
Ctensor T;
Tensor TLorentz, TLorentzC;
Ctensor fcol(antisymmetric); 

*Dummy variables and functions
symbols [];
autodeclare symbols   aux;
autodeclare vector    HelpV;
autodeclare functions HelpF;
autodeclare index     HelpI = 0;

cfunctions ColTr(cyclic), TProduct, SpinorCNumber, SpinorCNumberC, Sp(symmetric);



autodeclare symbols ColFactor, Pentabox;




autodeclare symbols ProjectorCoefficient, GRAMProjector;
tensors ProjectorTensor, ProjectorTensorC;


autodeclare function ConjugatedExternal;

autodeclare symbols  PentaboxGGtoTTHTopology;



*It is important to put the dimension command after the definition of the Lorentzindices, if the indices have an associated dimension like col = 8, the dimension command has no influence. Only exception is mu = 0. When summed over mu the dimension command is still valid
Dimension D;

.global
